revert-husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,3 +6,7 @@ npm run lint:fix
 
 git add .
 
+if [ -f "yarn.lock" ] || [ -f "package-lock.json" ]; then
+  echo "Error: yarn.lock or package-lock.json is present. Please remove them before committing."
+  exit 1
+fi
